### ISSUE TITLE
Remove http crate dependency

### ISSUE THREAD

**Issue by NullSense** [MrCappuccino/Linda#10]
Having the http crate as a dependency defeats the purpose of Linda: a *minimal* http/1.1 server implementation. The only current use of http is for status codes.

To remove the dependency a simple status code enum needs to be created according to the [http/1.1 spec RFC2616](https://tools.ietf.org/html/rfc2616#section-6.1.1).

**Comment by okrplay** [comment]
I'll try to solve this 👍

**Comment by NullSense** [comment]
Go ahead! If there are any design decisions or hiccups, don't hesitate to comment on the issue. Please include documentation and unit tests if applicable.
